export const loginFormConstant = {
  initialFormData: {
    thoughtMetricsId: '',
    password: '',
    rememberMe: false,
  },
  storeName: 'login-form-store',
  validationMessages: {
    thoughtMetricsId: 'Thought Metrics ID is required',
    password: 'Password is required',
    loginError: 'Invalid credentials. Please check your ID and password.',
    submitError: 'Login failed. Please try again.',
  },
  formResetDelay: 1000,
  apiSimulationDelay: 1500,
  ui: {
    pageTitle: 'Log in to Thought Metrics',
    fieldLabels: {
      thoughtMetricsId: 'Thought Metrics ID',
      password: 'Password',
    },
    checkboxLabels: {
      rememberMe: 'Remember me',
    },
    buttons: {
      continue: 'Continue',
      continuing: 'Signing in...',
      createAccount: 'Create a Thought Metrics ID',
    },
    links: {
      noAccount: "Don't have an account?",
      resetPassword: 'Click here',
      createAccount: 'Create a Thought Metrics ID',
    },
    successMessage: {
      title: 'Welcome Back!',
      description: 'You have successfully logged in to Thought Metrics.',
    },
  },
};

export const signUpFormConstant = {
  initialFormData: {
    firstName: '',
    lastName: '',
    address1: '',
    address2: '',
    email: '',
    phone: '',
    city: '',
    state: '',
    password: '',
    confirmPassword: '',
    zipCode: '',
    dateOfBirth: {
      month: '',
      day: '',
      year: '',
    },
    participationPreferences: [],
    termsAccepted: false,
    privacyAccepted: false,
  },
  participationOptions: [
    {
      id: 'thoughtMetricsFacilities',
      label: 'Interviews at Thought Metrics facilities',
    },
    { id: 'phoneInterviews', label: 'Phone Interviews' },
    { id: 'onlineInterviews', label: 'Online Interviews' },
    { id: 'interviewsAtHome', label: 'Interviews at my home' },
    { id: 'localBusinesses', label: 'Interviews at local businesses' },
  ],
  months: [
    { value: '01', label: 'January' },
    { value: '02', label: 'February' },
    { value: '03', label: 'March' },
    { value: '04', label: 'April' },
    { value: '05', label: 'May' },
    { value: '06', label: 'June' },
    { value: '07', label: 'July' },
    { value: '08', label: 'August' },
    { value: '09', label: 'September' },
    { value: '10', label: 'October' },
    { value: '11', label: 'November' },
    { value: '12', label: 'December' },
  ],
  states: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
  ],
  countryCodes: [
    { code: '+91', country: 'India' },
    { code: '+1', country: 'USA' },
    { code: '+44', country: 'UK' },
  ],
  defaultCountryCode: '+91',
  storeName: 'registration-form-store',
  validationMessages: {
    firstName: 'First name is required',
    lastName: 'Last name is required',
    email: {
      required: 'Email is required',
      invalid: 'Email is invalid',
    },
    password: 'Password is required',
    confirmPassword: {
      required: 'Please confirm your password',
      mismatch: 'Passwords do not match',
    },
    address1: 'Address is required',
    city: 'City is required',
    state: 'State is required',
    zipCode: 'Zip code is required',
    dateOfBirth: 'Date of birth is required',
    termsAccepted: 'You must accept the terms and conditions',
    privacyAccepted: 'You must accept the privacy policy',
    submitError: 'Registration failed. Please try again.',
  },
  emailRegex: '\\S+@\\S+\\.\\S+',
  formResetDelay: 3000,
  apiSimulationDelay: 2000,
  ui: {
    pageTitle: 'Create an Account',
    whyRegister: 'Why Register?',
    registerDescription:
      'Register using the form or data from on the services below.',
    socialButtons: {
      facebook: 'Continue with Facebook',
      google: 'Continue with Google',
    },
    steps: {
      step1: {
        number: 'Step 1',
        title: 'Your Information',
        active: true,
      },
      step2: {
        number: 'Step 2',
        title: 'Preferences',
        active: false,
      },
      step3: {
        number: 'Step 3',
        title: 'Surveys',
        active: false,
      },
    },
    fieldLabels: {
      firstName: 'First name',
      lastName: 'Last name',
      address1: 'Address 1',
      address2: 'Address 2',
      email: 'Email',
      phone: 'Phone (Optional)',
      city: 'City',
      state: 'State',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      zipCode: 'Zip Code',
      dateOfBirth: 'Date of Birth',
    },
    preferences: {
      title: 'Participation Preferences',
      description:
        'Are there any types of studies in which you would not like to participate? If so unselect them below.',
    },
    checkboxLabels: {
      termsAccepted:
        'I have read and understand my responsibilities as a participant and I agree to the TERMS AND CONDITIONS',
      privacyAccepted:
        'By clicking "Next", you are agreeing to Thought Metrics PRIVACY POLICY for receiving survey invitations for purposes of collection, compilation of demographic and attitudinal information and length of data retention. If you have provided your phone number to Thought Metrics, you agree to that Thought Metrics and its clients may call and send text messages for project-related purposes. You may revise your consent at any time.',
    },
    buttons: {
      next: 'Next',
      register: 'Register',
      processing: 'Processing...',
    },
    notes: {
      requiredFields: '* denotes required field',
    },
    successMessage: {
      title: 'Welcome to Thought Metrics!',
      description:
        'Your account has been created successfully. You can now participate in research studies and surveys.',
    },
  },
};
