// Country codes with flag emoji, dial code, and expected phone digit length
export interface CountryCode {
  code: string;   // e.g. '+91'
  name: string;
  flag: string;
  length?: number; // expected digit count (undefined = fallback to 7–15)
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: '+93', name: 'Afghanistan', flag: '🇦🇫', length: 9 },
  { code: '+355', name: 'Albania', flag: '🇦🇱', length: 9 },
  { code: '+213', name: 'Algeria', flag: '🇩🇿', length: 9 },
  { code: '+1', name: 'American Samoa', flag: '🇦🇸', length: 10 },
  { code: '+376', name: 'Andorra', flag: '🇦🇩', length: 6 },
  { code: '+244', name: 'Angola', flag: '🇦🇴', length: 9 },
  { code: '+1', name: 'Anguilla', flag: '🇦🇮', length: 10 },
  { code: '+1', name: 'Antigua and Barbuda', flag: '🇦🇬', length: 10 },
  { code: '+54', name: 'Argentina', flag: '🇦🇷', length: 10 },
  { code: '+374', name: 'Armenia', flag: '🇦🇲', length: 8 },
  { code: '+297', name: 'Aruba', flag: '🇦🇼', length: 7 },
  { code: '+61', name: 'Australia', flag: '🇦🇺', length: 9 },
  { code: '+43', name: 'Austria', flag: '🇦🇹', length: 10 },
  { code: '+994', name: 'Azerbaijan', flag: '🇦🇿', length: 9 },
  { code: '+1', name: 'Bahamas', flag: '🇧🇸', length: 10 },
  { code: '+973', name: 'Bahrain', flag: '🇧🇭', length: 8 },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩', length: 10 },
  { code: '+1', name: 'Barbados', flag: '🇧🇧', length: 10 },
  { code: '+375', name: 'Belarus', flag: '🇧🇾', length: 9 },
  { code: '+32', name: 'Belgium', flag: '🇧🇪', length: 9 },
  { code: '+501', name: 'Belize', flag: '🇧🇿', length: 7 },
  { code: '+229', name: 'Benin', flag: '🇧🇯', length: 8 },
  { code: '+1', name: 'Bermuda', flag: '🇧🇲', length: 10 },
  { code: '+975', name: 'Bhutan', flag: '🇧🇹', length: 8 },
  { code: '+591', name: 'Bolivia', flag: '🇧🇴', length: 8 },
  { code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦', length: 8 },
  { code: '+267', name: 'Botswana', flag: '🇧🇼', length: 8 },
  { code: '+55', name: 'Brazil', flag: '🇧🇷', length: 10 },
  { code: '+673', name: 'Brunei', flag: '🇧🇳', length: 7 },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬', length: 9 },
  { code: '+226', name: 'Burkina Faso', flag: '🇧🇫', length: 8 },
  { code: '+257', name: 'Burundi', flag: '🇧🇮', length: 8 },
  { code: '+855', name: 'Cambodia', flag: '🇰🇭', length: 8 },
  { code: '+237', name: 'Cameroon', flag: '🇨🇲', length: 9 },
  { code: '+1', name: 'Canada', flag: '🇨🇦', length: 10 },
  { code: '+238', name: 'Cape Verde', flag: '🇨🇻' },
  { code: '+1', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+236', name: 'Central African Republic', flag: '🇨🇫' },
  { code: '+235', name: 'Chad', flag: '🇹🇩' },
  { code: '+56', name: 'Chile', flag: '🇨🇱' },
  { code: '+86', name: 'China', flag: '🇨🇳' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴' },
  { code: '+269', name: 'Comoros', flag: '🇰🇲' },
  { code: '+243', name: 'Congo (DRC)', flag: '🇨🇩' },
  { code: '+242', name: 'Congo (Republic)', flag: '🇨🇬' },
  { code: '+506', name: 'Costa Rica', flag: '🇨🇷', length: 8 },
  { code: '+385', name: 'Croatia', flag: '🇭🇷', length: 9 },
  { code: '+53', name: 'Cuba', flag: '🇨🇺', length: 8 },
  { code: '+357', name: 'Cyprus', flag: '🇨🇾', length: 8 },
  { code: '+420', name: 'Czech Republic', flag: '🇨🇿', length: 9 },
  { code: '+45', name: 'Denmark', flag: '🇩🇰', length: 8 },
  { code: '+253', name: 'Djibouti', flag: '🇩🇯', length: 8 },
  { code: '+1', name: 'Dominica', flag: '🇩🇲', length: 10 },
  { code: '+1', name: 'Dominican Republic', flag: '🇩🇴', length: 10 },
  { code: '+593', name: 'Ecuador', flag: '🇪🇨', length: 9 },
  { code: '+20', name: 'Egypt', flag: '🇪🇬', length: 10 },
  { code: '+503', name: 'El Salvador', flag: '🇸🇻', length: 8 },
  { code: '+240', name: 'Equatorial Guinea', flag: '🇬🇶', length: 9 },
  { code: '+291', name: 'Eritrea', flag: '🇪🇷', length: 7 },
  { code: '+372', name: 'Estonia', flag: '🇪🇪', length: 7 },
  { code: '+251', name: 'Ethiopia', flag: '🇪🇹', length: 9 },
  { code: '+679', name: 'Fiji', flag: '🇫🇯', length: 7 },
  { code: '+358', name: 'Finland', flag: '🇫🇮', length: 9 },
  { code: '+33', name: 'France', flag: '🇫🇷', length: 9 },
  { code: '+241', name: 'Gabon', flag: '🇬🇦', length: 8 },
  { code: '+220', name: 'Gambia', flag: '🇬🇲', length: 7 },
  { code: '+995', name: 'Georgia', flag: '🇬🇪', length: 9 },
  { code: '+49', name: 'Germany', flag: '🇩🇪', length: 10 },
  { code: '+233', name: 'Ghana', flag: '🇬🇭', length: 9 },
  { code: '+30', name: 'Greece', flag: '🇬🇷', length: 10 },
  { code: '+1', name: 'Grenada', flag: '🇬🇩', length: 10 },
  { code: '+502', name: 'Guatemala', flag: '🇬🇹', length: 8 },
  { code: '+224', name: 'Guinea', flag: '🇬🇳', length: 9 },
  { code: '+245', name: 'Guinea-Bissau', flag: '🇬🇼', length: 7 },
  { code: '+592', name: 'Guyana', flag: '🇬🇾', length: 7 },
  { code: '+509', name: 'Haiti', flag: '🇭🇹', length: 8 },
  { code: '+504', name: 'Honduras', flag: '🇭🇳', length: 8 },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰', length: 8 },
  { code: '+36', name: 'Hungary', flag: '🇭🇺', length: 9 },
  { code: '+354', name: 'Iceland', flag: '🇮🇸', length: 7 },
  { code: '+91', name: 'India', flag: '🇮🇳', length: 10 },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩', length: 10 },
  { code: '+98', name: 'Iran', flag: '🇮🇷', length: 10 },
  { code: '+964', name: 'Iraq', flag: '🇮🇶', length: 10 },
  { code: '+353', name: 'Ireland', flag: '🇮🇪', length: 9 },
  { code: '+972', name: 'Israel', flag: '🇮🇱', length: 9 },
  { code: '+39', name: 'Italy', flag: '🇮🇹', length: 10 },
  { code: '+225', name: 'Ivory Coast', flag: '🇨🇮', length: 8 },
  { code: '+1', name: 'Jamaica', flag: '🇯🇲', length: 10 },
  { code: '+81', name: 'Japan', flag: '🇯🇵', length: 10 },
  { code: '+962', name: 'Jordan', flag: '🇯🇴', length: 9 },
  { code: '+7', name: 'Kazakhstan', flag: '🇰🇿', length: 10 },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', length: 9 },
  { code: '+686', name: 'Kiribati', flag: '🇰🇮', length: 5 },
  { code: '+965', name: 'Kuwait', flag: '🇰🇼', length: 8 },
  { code: '+996', name: 'Kyrgyzstan', flag: '🇰🇬', length: 9 },
  { code: '+856', name: 'Laos', flag: '🇱🇦', length: 8 },
  { code: '+371', name: 'Latvia', flag: '🇱🇻', length: 8 },
  { code: '+961', name: 'Lebanon', flag: '🇱🇧', length: 8 },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸', length: 8 },
  { code: '+231', name: 'Liberia', flag: '🇱🇷', length: 7 },
  { code: '+218', name: 'Libya', flag: '🇱🇾', length: 9 },
  { code: '+423', name: 'Liechtenstein', flag: '🇱🇮', length: 7 },
  { code: '+370', name: 'Lithuania', flag: '🇱🇹', length: 8 },
  { code: '+352', name: 'Luxembourg', flag: '🇱🇺', length: 9 },
  { code: '+853', name: 'Macau', flag: '🇲🇴', length: 8 },
  { code: '+389', name: 'Macedonia', flag: '🇲🇰', length: 8 },
  { code: '+261', name: 'Madagascar', flag: '🇲🇬', length: 9 },
  { code: '+265', name: 'Malawi', flag: '🇲🇼', length: 9 },
  { code: '+60', name: 'Malaysia', flag: '🇲🇾', length: 9 },
  { code: '+960', name: 'Maldives', flag: '🇲🇻', length: 7 },
  { code: '+223', name: 'Mali', flag: '🇲🇱', length: 8 },
  { code: '+356', name: 'Malta', flag: '🇲🇹', length: 8 },
  { code: '+692', name: 'Marshall Islands', flag: '🇲🇭', length: 7 },
  { code: '+222', name: 'Mauritania', flag: '🇲🇷', length: 8 },
  { code: '+230', name: 'Mauritius', flag: '🇲🇺', length: 8 },
  { code: '+52', name: 'Mexico', flag: '🇲🇽', length: 10 },
  { code: '+691', name: 'Micronesia', flag: '🇫🇲', length: 7 },
  { code: '+373', name: 'Moldova', flag: '🇲🇩', length: 8 },
  { code: '+377', name: 'Monaco', flag: '🇲🇨', length: 8 },
  { code: '+976', name: 'Mongolia', flag: '🇲🇳', length: 8 },
  { code: '+382', name: 'Montenegro', flag: '🇲🇪', length: 8 },
  { code: '+212', name: 'Morocco', flag: '🇲🇦', length: 9 },
  { code: '+258', name: 'Mozambique', flag: '🇲🇿', length: 9 },
  { code: '+95', name: 'Myanmar', flag: '🇲🇲', length: 9 },
  { code: '+264', name: 'Namibia', flag: '🇳🇦', length: 9 },
  { code: '+674', name: 'Nauru', flag: '🇳🇷', length: 7 },
  { code: '+977', name: 'Nepal', flag: '🇳🇵', length: 10 },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱', length: 9 },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿', length: 9 },
  { code: '+505', name: 'Nicaragua', flag: '🇳🇮', length: 8 },
  { code: '+227', name: 'Niger', flag: '🇳🇪', length: 8 },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬', length: 10 },
  { code: '+850', name: 'North Korea', flag: '🇰🇵', length: 10 },
  { code: '+47', name: 'Norway', flag: '🇳🇴', length: 8 },
  { code: '+968', name: 'Oman', flag: '🇴🇲', length: 8 },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', length: 10 },
  { code: '+680', name: 'Palau', flag: '🇵🇼', length: 7 },
  { code: '+970', name: 'Palestine', flag: '🇵🇸', length: 9 },
  { code: '+507', name: 'Panama', flag: '🇵🇦', length: 8 },
  { code: '+675', name: 'Papua New Guinea', flag: '🇵🇬', length: 8 },
  { code: '+595', name: 'Paraguay', flag: '🇵🇾', length: 9 },
  { code: '+51', name: 'Peru', flag: '🇵🇪', length: 9 },
  { code: '+63', name: 'Philippines', flag: '🇵🇭', length: 10 },
  { code: '+48', name: 'Poland', flag: '🇵🇱', length: 9 },
  { code: '+351', name: 'Portugal', flag: '🇵🇹', length: 9 },
  { code: '+1', name: 'Puerto Rico', flag: '🇵🇷', length: 10 },
  { code: '+974', name: 'Qatar', flag: '🇶🇦', length: 8 },
  { code: '+40', name: 'Romania', flag: '🇷🇴', length: 9 },
  { code: '+7', name: 'Russia', flag: '🇷🇺', length: 10 },
  { code: '+250', name: 'Rwanda', flag: '🇷🇼', length: 9 },
  { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦', length: 9 },
  { code: '+221', name: 'Senegal', flag: '🇸🇳', length: 9 },
  { code: '+381', name: 'Serbia', flag: '🇷🇸', length: 9 },
  { code: '+248', name: 'Seychelles', flag: '🇸🇨', length: 7 },
  { code: '+232', name: 'Sierra Leone', flag: '🇸🇱', length: 8 },
  { code: '+65', name: 'Singapore', flag: '🇸🇬', length: 8 },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰', length: 9 },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮', length: 8 },
  { code: '+677', name: 'Solomon Islands', flag: '🇸🇧', length: 7 },
  { code: '+252', name: 'Somalia', flag: '🇸🇴', length: 8 },
  { code: '+27', name: 'South Africa', flag: '🇿🇦', length: 9 },
  { code: '+82', name: 'South Korea', flag: '🇰🇷', length: 10 },
  { code: '+211', name: 'South Sudan', flag: '🇸🇸', length: 9 },
  { code: '+34', name: 'Spain', flag: '🇪🇸', length: 9 },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', length: 9 },
  { code: '+249', name: 'Sudan', flag: '🇸🇩', length: 9 },
  { code: '+597', name: 'Suriname', flag: '🇸🇷', length: 7 },
  { code: '+268', name: 'Swaziland', flag: '🇸🇿', length: 8 },
  { code: '+46', name: 'Sweden', flag: '🇸🇪', length: 9 },
  { code: '+41', name: 'Switzerland', flag: '🇨🇭', length: 9 },
  { code: '+963', name: 'Syria', flag: '🇸🇾', length: 9 },
  { code: '+886', name: 'Taiwan', flag: '🇹🇼', length: 9 },
  { code: '+992', name: 'Tajikistan', flag: '🇹🇯', length: 9 },
  { code: '+255', name: 'Tanzania', flag: '🇹🇿', length: 9 },
  { code: '+66', name: 'Thailand', flag: '🇹🇭', length: 9 },
  { code: '+670', name: 'Timor-Leste', flag: '🇹🇱', length: 8 },
  { code: '+228', name: 'Togo', flag: '🇹🇬', length: 8 },
  { code: '+676', name: 'Tonga', flag: '🇹🇴', length: 7 },
  { code: '+1', name: 'Trinidad and Tobago', flag: '🇹🇹', length: 10 },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳', length: 8 },
  { code: '+90', name: 'Turkey', flag: '🇹🇷', length: 10 },
  { code: '+993', name: 'Turkmenistan', flag: '🇹🇲', length: 8 },
  { code: '+688', name: 'Tuvalu', flag: '🇹🇻', length: 7 },
  { code: '+256', name: 'Uganda', flag: '🇺🇬', length: 9 },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦', length: 9 },
  { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪', length: 9 },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧', length: 10 },
  { code: '+1', name: 'United States', flag: '🇺🇸', length: 10 },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', length: 8 },
  { code: '+998', name: 'Uzbekistan', flag: '🇺🇿', length: 9 },
  { code: '+678', name: 'Vanuatu', flag: '🇻🇺', length: 7 },
  { code: '+58', name: 'Venezuela', flag: '🇻🇪', length: 10 },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', length: 9 },
  { code: '+967', name: 'Yemen', flag: '🇾🇪', length: 9 },
  { code: '+260', name: 'Zambia', flag: '🇿🇲', length: 9 },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼', length: 9 },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES.find(c => c.name === 'India')!;
